CREATE TYPE "categories_filters" AS ENUM (
  'development',
  'business',
  'finance_and_accounting',
  'computing_and_software',
  'productivity_in_the_office'
);

CREATE TYPE "instructor" AS ENUM (
  'instructor_a',
  'instructor_b',
  'instructor_c'
);

CREATE TYPE "levels" AS ENUM (
  'basic',
  'intermediate',
  'advance'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar UNIQUE NOT NULL,
  "phone" varchar,
  "birthday" date
);

CREATE TABLE "profiles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country" varchar,
  "address_1" varchar,
  "address_2" varchar,
  "zip" int,
  "user_id" int
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "level" levels,
  "author" instructor,
  "duration" int,
  "publication_date" date,
  "url" varchar,
  "user_id" int
);

CREATE TABLE "courses_videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "url" varchar UNIQUE NOT NULL,
  "id_videos" int
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" categories_filters,
  "id_categories" int
);

ALTER TABLE "courses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "courses_videos" ADD FOREIGN KEY ("id_videos") REFERENCES "courses" ("id");

ALTER TABLE "categories" ADD FOREIGN KEY ("id_categories") REFERENCES "courses_videos" ("id");


insert into users (
  first_name,
  last_name,
  email,
  password,
  phone,
  birthday
) values (
  'pedro',
  'Alvaréz',
  'pedro@correo.com',
  'root',
  '+52984851691',
  '28/08/2000'
);

insert into users (
  first_name,
  last_name,
  email,
  password,
  phone,
  birthday
) values (
  'Jusue',
  'Gallardo',
  'Josue@correo.com',
  'root2',
  '+52984855691',
  '28/08/2000'
);

insert into users (
  first_name,
  last_name,
  email,
  password,
  phone,
  birthday
) values (
  'Ulices',
  'Aguila',
  'Uli@correo.com',
  'root3',
  '+52984851661',
  '13/01/1998'
);




insert into profiles (
country,
address_1,
address_2,
zip,
user_id 
) values (
'México',
'Address1',
'Address2',
'56880',
'1'
) , (
'El salvador',
'Address1',
'Address2',
'04031',
'2'
) , (
'México',
'Address1',
'Address2',
'56248',
'3'
);



insert into courses (
title,
description,
"level",
author,
duration,
publication_date,
url,
user_id 
) values (
'python',
'Aprende el Lenguaje de Programación Web más popular',
'intermediate',
'instructor_b',
'30',
'12/01/2023',
'https://www.udemy.com/course/javascript-moderno-guia-definitiva-construye-10-proyectos/',
'1'
) , (
'c++',
'Aprende el Lenguaje de Programación Web más popular',
'advance',
'instructor_c',
'20',
'12/01/2023',
'https://www.udemy.com/course/javascript-moderno-guia-definitiva-construye-20-proyectos/',
'2'
) , (
'JavaScript',
'Aprende el Lenguaje de Programación Web más popular',
'basic',
'instructor_a',
'50',
'12/01/2023',
'https://www.udemy.com/course/javascript-moderno-guia-definitiva-construye-40-proyectos/',
'3'
);



insert into courses_videos (
title,
url,
id_videos
) values (
'JavaScript Moderno',
'https://www.udemy.com/course/javascript-moderno-guia-definitiva-construye-10-proyectos/',
'1'
) , (
'Tailwind',
'https://www.udemy.com/course/javascript-moderno-guia-definitiva-construye-11-proyectos/',
'2'
) , (
'Python',
'https://www.udemy.com/course/javascript-moderno-guia-definitiva-construye-12-proyectos/',
'3'
);

insert into categories (
"name",
id_categories 
) values (
'development',
'1'
);

insert into categories (
"name",
id_categories 
) values (
'computing_and_software',
'2'
) , (
'business',
'3'
);










